// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0

package authors

import (
	"database/sql"
	"time"
)

type Account struct {
	ID           int64
	Owner        string
	Balance      int64
	Currency     string
	CreatedAt    time.Time
	CounteryCode int32
}

type Entry struct {
	ID        int64
	AccountID sql.NullInt64
	Amount    int64
	CreatedAt time.Time
}

type Transfer struct {
	ID            int64
	FromAccountID sql.NullInt64
	ToAccountID   sql.NullInt64
	Amount        int64
	CreatedAt     time.Time
}
